/*
2020  B18030616 & B18030620 & B18030626 with The Unlicense
For more information, please refer to <https://unlicense.org>
 */
package cc.amzrk2.digiclock;

import java.awt.*;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;

public class DigiClock extends JFrame implements Runnable {

    public ClockDrawPanel clockPanel; // 数字钟主显示 Panel
    public Thread clockThread; // 时钟运作线程
    public int xCAxis; // 数字钟主显示 Panel 中心点 x 坐标
    public int yCAxis; // 数字钟主显示 Panel 中心点 y 坐标
    public Font clockPanelFont = new Font("Arial", Font.BOLD, 72); // 数字钟主显示 Panel 字体

    public DigiClock() {
        initComponents(); // 初始化 NetBeans 生成组件
        initClockDrawPanel(); // 初始化自定义数字钟主显示 Panel
        xCAxis = clockPanel.getWidth() / 2; // 数字钟主显示 Panel 中心点 x 坐标
        yCAxis = clockPanel.getHeight() / 2 - 15; // 数字钟主显示 Panel 中心点 x 坐标
        // 启动时钟运作线程
        clockThread = new Thread(this, "clockThread");
        clockThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("数字时钟");
        setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        setResizable(false);

        jMenuBar1.setFont(getFont());

        jMenu1.setText("File");
        jMenu1.setFont(getFont());
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(getFont());
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 初始化自定义数字钟主显示 Panel
    private void initClockDrawPanel() {
        clockPanel = new ClockDrawPanel();
        clockPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2)); // 边框
        clockPanel.setPreferredSize(new Dimension(740, 150)); // 设置主显 Panel 大小
        // 将主显 Panel 加入 mainFrame 的 layout
        // mainFrame 的 layout 已于 initComponents() 中修改过，这里获取并修改
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        // 左右 30px
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30).addComponent(clockPanel).addGap(30, 30, 30))
        );
        // 上 30px 下 max 420px
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30).addComponent(clockPanel).addContainerGap(420, Short.MAX_VALUE))
        );
        pack();
    }

    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DigiClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DigiClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DigiClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DigiClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        DigiClock clock = new DigiClock();
        clock.setVisible(true);
    }

    // 时钟运作线程
    @Override
    public void run() {
        Thread thisThread = Thread.currentThread();
        while (clockThread == thisThread) {
            clockPanel.repaint();
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }

    // 自定义数字钟主显示 Panel
    class ClockDrawPanel extends JPanel {

        // 重写 paintComponent 避免闪烁
        public void paintComponent(Graphics mg) {
            // 转换为 G2D 方便使用高级设置
            Graphics2D g2d = (Graphics2D) mg;
            // 开启字体抗锯齿
            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            super.paintComponent(g2d);
            // 设置线条粗细和字体
            g2d.setStroke(new BasicStroke(2f));
            g2d.setFont(clockPanelFont);
            // 获取当前日期和时间
            Calendar cal = Calendar.getInstance();
            // 绘制字符串显示的日期和时间
            String date = (new SimpleDateFormat("yyyy-MM-dd")).format(cal.getTime());
            String time = (new SimpleDateFormat("HH:mm:ss")).format(cal.getTime());
            // 居中绘制字符串
            FontMetrics dateFm = g2d.getFontMetrics(clockPanelFont);
            int fontHeight = dateFm.getHeight(); // 字体高度
            int dateWidth = dateFm.stringWidth(date); // 各字符串宽度
            int timeWidth = dateFm.stringWidth(time);
            g2d.drawString(time, xCAxis / 2 - timeWidth / 2, yCAxis + fontHeight / 2);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
